name: Build

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    #
    # Set up Python
    #

    - name: Set up Python 3.10
      uses: actions/setup-python@v1
      with:
        python-version: 3.10

    #
    # Install Python dependencies
    #

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    #
    # Lint
    #

    - name: Lint Python code with flake8
      run: flake8

    #
    # Run tests
    #

    - name: Run unit tests
      run: python -m unittest test.envargs_test.EnvParserTest

    #
    # Codecov
    #

    - name: Upload to Codecov
      run: |
        curl -Os https://uploader.codecov.io/latest/linux/codecov
        chmod +x codecov 
        ./codecov
